### ISSUE TITLE
Python Enviroment Recognize Problem

### ISSUE THREAD

**Issue by serenitydevs** [ysrc/xunfeng#110]
Hi,so after doing all your "tutorial" i tryed to install "xunfeng" but it keep saying that "Python 2.7.x" is not found,i made an update for python and it says "python is already the newest version (2.7.13-2)",any fix for this?

**Comment by Medicean** [comment]
@serenitydevs Can you provide your operating system release information? Windows, Debian 8 , CentOS 7 ?

**Comment by ihacku** [comment]
@serenitydevs pls try again
