### ISSUE TITLE
无法配置扫描引擎和爬虫引擎

### ISSUE THREAD

**Issue by mingjer** [ysrc/xunfeng#111]
如题，无法选择配置引擎，统计处两个引擎为x号
scan.log报错：
'NoneType' object has no attribute '__getitem__'
vul.log报错：
'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "./vulscan/VulScan.py", line 260, in <module>
    PASSWORD_DIC, THREAD_COUNT, TIMEOUT, WHITE_LIST = get_config()
TypeError: 'NoneType' object is not iterable
数据应该导入了：
> db.stats()
{
	"db" : "xunfeng",
	"collections" : 2,
	"objects" : 61,
	"avgObjSize" : 361.327868852459,
	"dataSize" : 22041,
	"storageSize" : 40960,
	"numExtents" : 0,
	"indexes" : 2,
	"indexSize" : 36864,
	"ok" : 1
}
还请ysrc的童鞋协助看看

**Comment by ihacku** [comment]
看下你的python版本

**Comment by ywolf** [comment]
数据库问题，mongodb 要求 >=3.2，重新导入一下。

**Comment by mingjer** [comment]
确实是数据没导进去，把readme的参考命令里的. 改为绝对路径就导入成功了，感谢各位
