### ISSUE TITLE
database error: not authorized for query on xunfeng.Config

### ISSUE THREAD

**Issue by wifislax** [ysrc/xunfeng#114]
运行环境windows7 ，按照Windows 安装指南一步一步下去，提示报错。密码设置正确，在单独使用db.auth（‘scan’，‘scanlol66’），成功扽登陆，执行脚本python nascan/NAScan.py ，提示databas eerro
![image](https://user-images.githubusercontent.com/22518233/28220802-7575a52a-68f3-11e7-8f68-46c9043e2be6.png)

**Comment by ywolf** [comment]
Config.py 看看

**Comment by wifislax** [comment]
class Config(object):
    ACCOUNT = 'admin'
    PASSWORD = 'admin'


class ProductionConfig(Config):
    DB = '127.0.0.1'
    PORT = 65521
    DBUSERNAME = 'scan'
    DBPASSWORD = 'scan'
    DBNAME = 'xunfeng'

**Comment by ywolf** [comment]
DBPASSWORD = 'scan'
改为
DBPASSWORD = 'scanlol66'

**Comment by wifislax** [comment]
database error: not authorized for query on xunfeng.Config ,一样的错误。是不是版本的问题 ？

**Comment by wifislax** [comment]
Failed to authenticate scan@xunfeng with mechanism MONGODB-CR: AuthenticationFailed: MONGODB-CR credentials missing in the user document
