### ISSUE TITLE
搜索结果翻页有bug，只能显示第一页内容，下一页或选之后的页都无结果

### ISSUE THREAD

**Issue by D884** [ysrc/xunfeng#122]

**Comment by D884** [comment]
地址http://127.0.0.1/?q=web?page=2第二个问号应该改为&即http://127.0.0.1/?q=web&page=2

**Comment by ihacku** [comment]
请问你的搜索关键词是？我刚看了下就是&page=2啊

**Comment by D884** [comment]
common.js里写的搜索关键词小于7位的时候是?page=2，大于7位的时候才是&page=2，不知道这个判定起什么作用？

**Comment by neargle** [comment]
感谢反馈，问题已修复，欢迎复测。
