### ISSUE TITLE
启动时问题

### ISSUE THREAD

**Issue by aaeolus** [ysrc/xunfeng#123]
xunfeng:xunfeng_aider: ERROR (spawn error)

**Comment by Medicean** [comment]
restart 试试，也可能是端口已经被占用了

**Comment by aaeolus** [comment]
解决了，是端口占用了

**Comment by IsTr33** [comment]
@aaeolus 请问是53端口被dnsmasq占用了吗，我遇到了这种情况，应该怎么解决呢？

**Comment by aaeolus** [comment]
重启就完了
