### ISSUE TITLE
python依赖库的问题

### ISSUE THREAD

**Issue by chaozai1028l** [ysrc/xunfeng#129]
原文提示，将端口和目录对应好
我安装好后， which mongod   显示在  /usr/bin/mongod
是不是就该把 XUNFENG_DB=/usr/bin/mongod
然后把端口 port 27017  
就OK了

**Comment by ihacku** [comment]
python get-pip.py -i https://pypi.doubanio.com/simple/
或者
python get-pip.py -i https://mirrors.aliyun.com/pypi/simple/

**Comment by ihacku** [comment]
Hi，新的问题请开新的 issue，不要在原有的 issue 上做更改。
