### ISSUE TITLE
try_web逻辑问题

### ISSUE THREAD

**Issue by LandGrey** [ysrc/xunfeng#135]
问题出在 xunfeng/nascan/lib/scan.py 文件中的try_web函数，
```
 if self.port == 443:
    info = urllib2.urlopen("https://%s:%s" % (self.ip, self.port), timeout=self.timeout)
else:
    info = urllib2.urlopen("http://%s:%s" % (self.ip, self.port), timeout=self.timeout)
```
忽略了开放在非443端口的使用https协议的情况，比如 https://www.example.com:8443/

**Comment by LandGrey** [comment]
类似的，xunfeng/nascan/lib/scan.py 文件中的discern函数，也存在逻辑不严谨的问题，会忽略掉少数一部分使用https协议的web端口，如8443，9443等；
不知道开发时是不是为了减少代码复杂度和影响比较小的原因，故意忽略的。
```
if int(domain.split(":")[1]) == 443:
    protocol = "https://"
else:
    protocol = "http://"
```

**Comment by ywolf** [comment]
权衡后的选择把，为了减少请求，只对443进行https的探测，如果所有端口都去尝试，得多消耗一倍的时间。
