### ISSUE TITLE
推送的插件：SHIRO 反序列化漏洞 安装失败

### ISSUE THREAD

**Issue by IsTr33** [ysrc/xunfeng#143]
插件信息--------------------------
插件名：SHIRO 反序列化漏洞
描述：漏洞的成因是Apache Commons Collections (ACC) 3.2.1及4.0版本未能正确验证用户输入，其InvokerTransformer类在反序列化来自可疑域的数据时存在安全漏洞，这可使攻击者在用户输入中附加恶意代码并组合运用不同类的readObject()方法，在最终类型检查之前执行Java函数或字节码（包括调用Runtime.exec()执行本地OS命令）。
作者：Dee Ng<d33.n99@gmail.com>

点击安装提示------------------------
安装失败，一定是姿势不对

请问什么原因造成的，我该如何修改？或者查看解决方法？

PS：Ubuntu 16.04 Linux自动安装的

**Comment by neargle** [comment]
打开chrome的console看一下有报错没

**Comment by IsTr33** [comment]
没有，console无任何输出。

**Comment by captain-zhou** [comment]
我也有这个错误，仅有这一个插件装不上。
打开firefox的控制台跟踪了下，有如下提示：
一个“警告”：getElementById() 被传递了空字符串参数。
一个“错误”：Content Security Policy: 页面设置阻止读取位于 https://www.google-analytics.com/collect?v=1&_v=j48&a=785143729&t=pageview&_s=1&dl=https%3A%2F%2Fgithub.com%2F%3Cuser-name%3E%2F%3Crepo-name%3E%2Fissues%2Fshow&ul=zh-cn&de=UTF-8&dt=(masked)&sd=24-bit&sr=1920x1080&vp=1901x971&je=0&fl=27.0%20r0&_u=SCCAAEABM~&jid=&cid=1990925019.1474877148&tid=UA-3769691-2&cd5=Logged%20In&cd1=Logged%20In&z=942328810 的一项资源("img-src https://github.com data: https://assets-cdn.github.com https://identicons.github.com https://collector.githubapp.com https://github-cloud.s3.amazonaws.com https://*.githubusercontent.com")。
不知道这两个提示是否相关，供参考。

**Comment by IsTr33** [comment]
@captain-zhou 我正在debug，后台写的try except 没try成功，我正在找原因。

**Comment by IsTr33** [comment]
找到原因了，是因为没装cryptography模块
解决：pip install cryptography

安装cryptography后插件成功安装。

**Comment by andytree** [comment]
@IsTr33 谢谢，可以了。
