### ISSUE TITLE
巡风的mongodb如何开启远程访问？

### ISSUE THREAD

**Issue by jbxsky** [ysrc/xunfeng#148]
RT，没找到对应的配置文件

**Comment by jbxsky** [comment]
我是centos 7，使用curl -sSL https://raw.githubusercontent.com/ysrc/xunfeng/master/install/install.sh | sh安装的，安装和使用没遇到什么问题。

**Comment by Medicean** [comment]
修改 `/etc/xunfeng.conf` 文件第25行：

https://github.com/ysrc/xunfeng/blob/master/install/files/xunfeng.conf#L25

**Comment by jbxsky** [comment]
能详细说明一下吗？我把bind_ip改成0.0.0.0或者本机IP都不好使，谢谢了

**Comment by Medicean** [comment]
```
--bind_ip arg                         comma separated list of ip addresses to
                                        listen on - all local ips by default
```

直接把 `--bind_ip 127.0.0.1` 这部分删掉就行了

**Comment by jbxsky** [comment]
好的，谢谢！

**Comment by jbxsky** [comment]
哦对了，还有一个问题，为了只能本机访问，能在/etc/xunfeng.conf中能把web绑定到127.0.0.1吗？是不是也要和db那样在xunfeng_web下加一个--bind_ip？还是把那个-b 0.0.0.0:80 改成-b 127.0.0.1:80

**Comment by jbxsky** [comment]
试了一下是把-b 0.0.0.0:80改成-b 127.0.0.1:80就能限制仅本机访问web了，还是谢谢了！
