### ISSUE TITLE
请问巡风如何更新？

### ISSUE THREAD

**Issue by ehui168** [ysrc/xunfeng#150]
当时是通过一句话命令自动安装的，请问安装后的巡风该如何更新程序，谢谢！

**Comment by ywolf** [comment]
程序可通过覆盖代码的方式，插件可通过接受推送的或者在web中添加，自动安装的目录为/opt/xunfeng/

**Comment by ehui168** [comment]
我直接下载了最新版0.2.0的压缩包解压后，将原安装目录下的/opt/xunfeng目录删除，替换最新版本到对应目录，目录名称和权限都没错，发现无法正常WEB访问，Telnet服务器80端口正常，请问还有那些地方需要调整处理？

**Comment by ywolf** [comment]
只覆盖代码   自动安装的 /opt/xunfeng 目录不止包含源码

**Comment by Medicean** [comment]
```
$ cd /opt/xunfeng
$ git pull
```
