### ISSUE TITLE
启用Masscan无法扫描

### ISSUE THREAD

**Issue by ehui168** [ysrc/xunfeng#151]
我的巡风是安装在Centos 7上，自动安装时默认在/opt/xunfeng/masscan/linux_64/目录下，按照指引也执行chmod +x给此目录增加权限，但只要一启用Masscan，等很久都没有扫描结果出来，请问问题到底出在哪里？

**Comment by ehui168** [comment]
这是设置截图

**Comment by Medicean** [comment]
猜想是 masscan 可能缺了某个 so 库，你先在命令行下手动执行 masscan 看是否有问题。

**Comment by ehui168** [comment]
![360 20180118120701872](https://user-images.githubusercontent.com/34931383/35080389-37aae21c-fc48-11e7-8541-c150d1ec754c.jpg)
手动执行命令可以扫描

**Comment by ywolf** [comment]
速率500 建议再调高点 如果你是扫描几百台机器的话 估计得好几个小时才完成

**Comment by ehui168** [comment]
谢谢，可以使用了。
