### ISSUE TITLE
关于添加扫描资产白名单

### ISSUE THREAD

**Issue by xizhimen** [ysrc/xunfeng#154]
效果如下: 
<img width="1357" alt="wx20180122-170028 2x" src="https://user-images.githubusercontent.com/19748550/35212661-dd5ede48-ff95-11e7-8fb7-310a5993c476.png">

需要对朋友可以按一下方式实现:

1、登录到mongo shell 下执行如下操作:
```use xunfeng```
```db.Config.update({"type" : "nascan"},{$set:{"config.White_list":{ "value" : "", "info" : "资产发现白名单", "help" : "不对白名单内的IP列表进行漏洞检测。格式：x.x.x.x，以行分割"}}})```

2、将./nascan/lib/start.py更新成如下
```
class start:
    def __init__(self, config):  # 默认配置
        self.config_ini = config
        self.queue = Queue.Queue()
        self.thread = int(self.config_ini['Thread'])
        self.scan_list = self.config_ini['Scan_list'].split('\n')
        self.mode = int(self.config_ini['Masscan'].split('|')[0])
        self.icmp = int(self.config_ini['Port_list'].split('|')[0])
        self.white_list = self.config_ini['White_list'].split('\n')    #新增

    def run(self):
        global AC_PORT_LIST
        all_ip_list = []
        for ip in self.scan_list:
            if "/" in ip: ip = cidr.CIDR(ip)
            if not ip:continue
            ip_list = self.get_ip_list(ip)
            for white_ip in self.white_list:    #新增
                if white_ip in ip_list:   #新增
                    ip_list.remove(white_ip)    #新增
            if self.mode == 1:
```

**#新增为注释 修改时可忽略**

**Comment by neargle** [comment]
根据这个建议 https://github.com/ysrc/xunfeng/pull/152 还是可以兼容的呀 不试试吗？

**Comment by neargle** [comment]
fix:https://github.com/ysrc/xunfeng/commit/67faef33c2ecb400b865a87c80cb8ffb4fbeb4c4  一直是心病 挂心了一个春节 现在fix了
