### ISSUE TITLE
一键默认安装，出现mongo本地连接登陆失败

### ISSUE THREAD

**Issue by dropslzx** [ysrc/xunfeng#163]
1、安装服务的机器为Ubuntu 14.04
2、安装过程为Linux一条命令安装
3、安装过程中的数据库名字和密码等弹窗操作的命名均为默认
但出现数据库登录失败的情况，如图所示。
[mongo本地连接](http://obh16g4rw.bkt.clouddn.com/RY2MKNWJX2@@4@%28%29E7%29YDGI.png)
[本地权限查看](http://obh16g4rw.bkt.clouddn.com/A~4SCG5~S1HQ%60@5_4XQK5$X.png)

**Comment by Medicean** [comment]
看你的截图，用的是 2.4.9 的 mongo, 你用 /opt/xunfeng/xunfengdb/ 下的 mongodb 看看？
