### ISSUE TITLE
docker下如何修改巡风登陆的用户名和密码

### ISSUE THREAD

**Issue by Mr89898** [ysrc/xunfeng#166]
[root@172-16-200-240 ~]# docker start condescending_boyd 
condescending_boyd
[root@172-16-200-240 ~]# docker start pedantic_mclean 
Error response from daemon: driver failed programming external connectivity on endpoint pedantic_mclean (122df7e833390ae307c798df07af2a874543c2f5ec44d9219b03ca79582098dc): Bind for 0.0.0.0:8000 failed: port is already allocated
Error: failed to start containers: pedantic_mclean

**Comment by Medicean** [comment]
关于标题说的修改配置参考 #95 

然后是贴的这个log，`failed: port is already allocated`是因为开了两个 container，都想绑定物理机的 8000 端口导致端口占用
