### ISSUE TITLE
docker pull 下镜像后无法挂载请问如何解决

### ISSUE THREAD

**Issue by Mr89898** [ysrc/xunfeng#170]
docker run -d -p 8000:80 -v /tmp:/data ysrc/xunfeng:latest
/usr/bin/docker-current: Error response from daemon: mkdir /var/lib/docker/overlay2/15e548b5a8d06174f662c641375981b179b4389bd48067fe7f9b06a3d95118e7-init/merged/dev/shm: invalid argument.
See '/usr/bin/docker-current run --help'.
docker.io/ysrc/xunfeng   latest              ae923235340d        2 weeks ago         704 MB

**Comment by Medicean** [comment]
@Mr89898 命令是正确的,没毛病,换一个目录试一下。
