### ISSUE TITLE
nascan/plugin/masscan.py 里需要过滤参数

### ISSUE THREAD

**Issue by lhtest429** [ysrc/xunfeng#18]
run(ip_list,path,rate)的rate在函数里过滤一下
类似：
path = str(path).translate(None, ';|&')

**rate = str(rate).translate(None, ';|&')**

**Comment by ywolf** [comment]
这个问题开始就已经意识到，但是考虑到新增插件的开放性，已经可以直接执行python代码，所以对后台功能未严格限制，不过既然提出就处理掉，稍后后台配置新增加CSRF的防御代码，这里也过滤一下。
