### ISSUE TITLE
一键安装出现BUG (CENTOS7)

### ISSUE THREAD

**Issue by blockchainguard** [ysrc/xunfeng#183]
Looking in indexes: http://pypi.douban.com/simple/
Requirement already up-to-date: pip in /usr/lib/python2.7/site-packages (18.1)
Requirement already up-to-date: pip in /usr/lib/python2.7/site-packages (18.1)
Looking in indexes: http://pypi.douban.com/simple/
Collecting meld3==1.0.0
Installing collected packages: meld3
  Found existing installation: meld3 0.6.10

Installing collected packages: meld3
  Found existing installation: meld3 0.6.10
Cannot uninstall 'meld3'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

------------
按要求卸载了还是不行？

**Comment by blockchainse** [comment]
注释掉了安装meld模块的代码安装成功
