### ISSUE TITLE
资产扫描没有反应

### ISSUE THREAD

**Issue by kunln** [ysrc/xunfeng#19]
你好，我安装的是docker容器的巡风，从昨天安装好，设定好资产列表和探测周期， 但是没有任何扫描结果，一个资产也没有啊。 是我什么地方出错了嘛？

**Comment by ywolf** [comment]
1.从统计页面看后端是否正常工作
2.资产列表IP段格式是否正确
3.如果开启了masscan，先确保masscan能正常工作。
4.如果探测目标存在防火墙，把icmp关闭掉。

**Comment by kunln** [comment]
您好，非常感谢您的邮件，我根据您邮件中的提示设置，还是没有结果，非常感谢您的解答。下面是我的设置,目标网网络没有防火墙：



姓 名：杜坤林
电 话：18380478268
Email：kunlindu@163.com
 
发件人： wolf
发送时间： 2016-12-23 12:23
收件人： ysrc/xunfeng
抄送： kunln; Author
主题： Re: [ysrc/xunfeng] 资产扫描没有反应 (#19)
1.从统计页面看后端是否正常工作
2.资产列表IP段格式是否正确
3.如果开启了masscan，先确保masscan能正常工作。
4.如果探测目标存在防火墙，把icmp关闭掉。

**Comment by ywolf** [comment]
查看下日志信息 是否有报错或者异常情况
