### ISSUE TITLE
Centos7下一条命令安装后连不上mongo

### ISSUE THREAD

**Issue by X1ng** [ysrc/xunfeng#191]
跟运维要的虚拟环境部署的。由于资产变动，而且之前加入了一些测试网段，删除任务后统计里漏洞还有显示，想在数据库里删除掉脏数据。可是问题来了。。找不到数据库装在哪。按照run.sh 应该在/var/lib/mongodb 下？目录里面没有啊，好多配置里写的mongo 端口65521 。但是在/opt/xunfeng/xunfengdb/bin]$./xunfeng_db 下出来的是27017啊。如果想访问数据库在哪搞啊

**Comment by Medicean** [comment]
```
$ cd /opt/xunfeng/xunfengdb/bin/
$ ./mongo 127.0.0.1:65521/xunfeng
```

**Comment by X1ng** [comment]
ths
