### ISSUE TITLE
这样写的规则对不对？

### ISSUE THREAD

**Issue by lianfeng30** [ysrc/xunfeng#2]
比如：
0|15
或者
1|15:30

貌似没开始

**Comment by ywolf** [comment]
格式为：
每几天|小时
例如 
1|10 即每天10点会进行资产扫描
7|15 即每7天15点会进行资产扫描

**Comment by lianfeng30** [comment]
0|*
看来是不行啦 tks

**Comment by lianfeng30** [comment]
对了
1|15:30 
这样的时间格式能识别不能？

**Comment by ywolf** [comment]
不可以 单位只能为小时

**Comment by lianfeng30** [comment]
恩 是的 
我刚才看了下代码。 tks
