### ISSUE TITLE
"网络资产探测列表"能否接受网段表示法

### ISSUE THREAD

**Issue by PaleCheung** [ysrc/xunfeng#22]
提示是 192.168.1.1-192.168.1.254

能否接受 192.168.1.0/24 呢？
毕竟 地址段的方法更标准，更专业。

还有 ipv6 也是用地址段表示，这个扯远了。

另外一个提升用户体验的优化。
统计试图里，服务数量统计，下面只是普通文本，如果可以直接做成超链接就更好了。

**Comment by ywolf** [comment]
可以的 后续增加上
