### ISSUE TITLE
xunfeng指纹规则版本问题

### ISSUE THREAD

**Issue by grayguest** [ysrc/xunfeng#223]
请教xunfeng的指纹能否加上版本信息呢？我看Language部分和webeye一样，我打算重写一下带版本的指纹规则，但是没有思路，想知道如果加上版本信息，应该从哪儿入手呢，xunfeng当时是怎么做的呐，希望前辈能指点一二。

**Comment by ywolf** [comment]
没有版本字段 如果要强行支持 也可以把版本号一并带入作为cms名 但这样不是很优雅

**Comment by grayguest** [comment]
谢谢wolf师父，优雅的问题如果抛开，把版本号和CMD名加在一起，我应该从哪些角度去收集这样的版本指纹规则呢？

**Comment by ywolf** [comment]
看你要的cms 更新log 推荐找 静态文件特征

**Comment by ywolf** [comment]
服务的话 大部分有banner的都自带版本信息了
