### ISSUE TITLE
扫描结果无法全选

### ISSUE THREAD

**Issue by Tim1995** [ysrc/xunfeng#229]
在批量扫描网段的时候，前提是：后台还在进行网段的资产探测（更新了资产一段时间，但是后台终端显示还在扫描，没有全部完成），通过搜索功能选取自己需要的结果，这个时候点击结果全选无法选中当前所有的结果，请问是不是设计的时候有点问题，还是只有全部资产探测完成才能进行结果的全选。

**Comment by ywolf** [comment]
结果集全选 没有前端效果 但实际上是选中的

**Comment by Tim1995** [comment]
后续会在前段实现效果的吧，目前我有什么方法去判断我是否选中了那些结果呢？

**Comment by ywolf** [comment]
结果集全选 就是 后台根据你搜索的关键字去取全部

**Comment by Tim1995** [comment]
因为他在前端没有体现的话，我点了一下结果集全选，我无法知道我是否有选择那些结果，例如我点击了一下1按钮，他前面出现了一个勾，我知道了我选中他了，现在我点击结果集全选，我无法判断出我是否有点中他。
