### ISSUE TITLE
任务页面总是500错误！

### ISSUE THREAD

**Issue by An93l** [ysrc/xunfeng#23]
任务页面总是500错误！
其他页面正常，任务页面建了4个任务！有时加载有些慢！然而还出现了500错误！日志里没有表现出那里的问题！

**Comment by ywolf** [comment]
任务的IP数量多少

**Comment by An93l** [comment]
10.0.0.0-10.0.255.255

**Comment by An93l** [comment]
@ywolf 大约2w左右的地址

**Comment by javert233** [comment]
任务列表页会列出每个任务的扫描范围(ip:port)，如果当前页面每个任务都没有进行准确的条件筛选或者添加任务的时候插件全选的话，页面上会有大量的ip端口信息从而导致500，如果确实扫描范围比较大的话，把显示ip端口的逻辑去除即可，具体的话就是把xunfeng/views/templates/task.html中60到63行去除，have a try
