### ISSUE TITLE
nse脚本识别需求

### ISSUE THREAD

**Issue by Jaic1** [ysrc/xunfeng#230]
> 感谢关注xunfeng项目，写得很好
> 目前xunfeng 资产探测 流程分为2种
> 1.自带的socket直接探测和指纹识别
> 2.先masscan快速探测出开放的端口，再使用socket进行二次判断和指纹识别
> 对于nmap定位应该为在masscan之后的二次判断和指纹识别，而不是跟它平等关系，又鉴于指纹配置自定义需求，也不准备使用nmap代替 socket+指纹识别 流程，因此此pr暂不合并，感谢关注

我目前在写扫描开放端口之后下一层的代码（你上面说的第一步），使用nmap加载nse脚本，对某些端口执行对应的识别和检测（建立端口和nse脚本的映射）。请问这个xunfeng有需要吗？

_Originally posted by @Jaic1 in https://github.com/ysrc/xunfeng/pull/227#issuecomment-533511388_

**Comment by Jaic1** [comment]
效果如下图：  
![](https://s2.ax1x.com/2019/09/22/uSOztO.png)
![](https://s2.ax1x.com/2019/09/22/uSOxAK.png)

**Comment by ihacku** [comment]
这样挺好的，复用下nse的脚本
