### ISSUE TITLE
 why cannot login to the container

### ISSUE THREAD

**Issue by GGOOHAPPY** [ysrc/xunfeng#234]
i deploy the  xunfeng using docker , but we cant login the the container ? what shell it is using 

#docker exec -it 7492518b742e bash
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"process_linux.go:75: starting setns process caused \\\"fork/exec /proc/self/exe: no such file or directory\\\"\"\n"
[root@hkgcvpd00389 containers]# docker exec -it 7492518b742e ash
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"process_linux.go:75: starting setns process caused \\\"fork/exec /proc/self/exe: no such file or directory\\\"\"\n"

**Comment by Medicean** [comment]
`/bin/bash`

**Comment by GGOOHAPPY** [comment]
it is still the same result

# docker ps -a
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS                    PORTS                  NAMES
7492518b742e        ysrc/xunfeng:latest   "/opt/xunfeng/dockerc"   5 days ago          Up 3 days                 0.0.0.0:9000->80/tcp   scan

# docker exec -it 7492518b742e /bin/bash
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"process_linux.go:75: starting setns process caused \\\"fork/exec /proc/self/exe: no such file or directory\\\"\"\n"

**Comment by Medicean** [comment]
maybe you should upgrade your docker engine

```
[root@debian]: /root
➜  docker ps                                                                                                                                               [2019-10-17 17:08:05]
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                   NAMES
54b92dbb4266        ysrc/xunfeng        "/opt/xunfeng/docker…"   About an hour ago   Up About an hour    0.0.0.0:32768->80/tcp   silly_beaver
[root@debian]: /root
➜  docker exec -it 54b92dbb4266 bash                                                                                                                       [2019-10-17 18:09:30]
root@54b92dbb4266:/opt/xunfeng#
```

**Comment by GGOOHAPPY** [comment]
what docker engine version it needs ?

**Comment by Medicean** [comment]
my docker version:

```
➜  docker version                                                                                                                                                                        [2019-10-21 14:12:36]
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:18 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:22:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```
