### ISSUE TITLE
请问无法每天自动扫描所有漏洞吗?

### ISSUE THREAD

**Issue by huangyonghome** [ysrc/xunfeng#238]
您好
我看演示视频介绍,貌似是要手动添加任务.比如我想扫ssh弱口令,那我加个弱口令任务(好像没有ssh弱口令插件)..我想扫mysql弱口令,那加个mysql弱口令任务
我想扫nginx.那加个NGINX

请问一下这样是不是很麻烦,我要针对每个具体漏洞要加任务..

能不能像Nessus那样用户只需要指定扫描哪个网段服务器,其他任何事情不需要操心..系统每天自动针对所有漏洞全表扫描?而不是用户指定你去扫哪个漏洞.因为很多漏洞用户也不知道啊.毕竟这方便不专业.

**Comment by LxKxC** [comment]
你搜“ip:”,然后显示所有的扫描结果，全选后，把插件全加进去不就行了吗？
nessus毕竟是商业化软件，肯定比开源的好用。

**Comment by huangyonghome** [comment]
@LxKxC 好的 .非常感谢
