### ISSUE TITLE
运行报错 爬虫引擎扫描引擎空白

### ISSUE THREAD

**Issue by linux997** [ysrc/xunfeng#27]
root@kali:~/xunfeng# python ./nascan/NAScan.py
'NoneType' object has no attribute '__getitem__'
root@kali:~/xunfeng# python ./vulscan/VulScan.py
'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "./vulscan/VulScan.py", line 258, in <module>
    PASSWORD_DIC, THREAD_COUNT, TIMEOUT, WHITE_LIST = get_config()
TypeError: 'NoneType' object is not iterable
root@kali:~/xunfeng#

**Comment by ywolf** [comment]
初始数据库没导入成功
