### ISSUE TITLE
mac安装xunfeng

### ISSUE THREAD

**Issue by Any3ite** [ysrc/xunfeng#28]
不帖图了，直接说步骤
1 安装homebrew   方法自行百度，这个有的
然后 使用 brew install   gcc  libffi libpcap openssl 
2安装mongodb
brew install mongodb
3克隆项目
git clone https://github.com/ysrc/xunfeng.git
之后切换到xunfeng的目录，使用pip 进行安装模块
sudo pip install pymongo Flask xlwt paramiko
4配置数据库
sudo mongod --port 65521 --dbpath /opt/xunfeng/log/db &
# DBData为数据库指定存在目录
sudo mongorestore -h 127.0.0.1 --port 65521 -d xunfeng  /opt/xunfeng/db
# db为初始数据库结构文件夹路径
# 低版本不支持全文索引，需使用高于 MongoDB 3.2版本
mongo --port 65521
use xunfeng
db.createUser({user:'scan',pwd:'123qweasdzxc',roles:[{role:'dbOwner',db:'xunfeng'}]})
exit    
#设置数据库密码为123qweasdzxc
5修改配置文件
把config.py里面的数据库密码替换成123qweasdzxc
之后修改run.sh文件把
XUNFENG_LOG=/var/log/xunfeng
XUNFENG_DB=/var/lib/mongodb
修改为
XUNFENG_LOG=/opt/xunfeng/log
XUNFENG_DB=/opt/xunfeng/log/db
之后再xunfeng的目录下建立log目录，并在log目录下建立db目录
之后保存
6启动巡风
sudo sh Run.sh

**Comment by ywolf** [comment]
感谢分享

**Comment by neargle** [comment]
为什么要发issue 可以整理一下 多点截图 发pull requests
