### ISSUE TITLE
新增插件 提示：新增失败 请检查数据是否完整或是否存在特殊字符! !

### ISSUE THREAD

**Issue by lianfeng30** [ysrc/xunfeng#42]
新增插件  json
提示：新增失败 请检查数据是否完整或是否存在特殊字符! !

[http://chuantu.biz/t5/45/1483606730x2074202128.png](url)

提示： 失败
[http://chuantu.biz/t5/45/1483606778x2074202128.png](url)

但是看下插件：
[http://chuantu.biz/t5/45/1483606807x2074202128.png](url)

居然显示有

是不是哪里错了？

还是/.git  这个.有问题？

**Comment by ywolf** [comment]
检测下vuldb目录是否有写权限，猜测是写入数据库成功但写入文件失败了。

**Comment by lianfeng30** [comment]
ok 我看看

**Comment by lianfeng30** [comment]
测试了 不是权限问题
json
添加
GET /.git

判断依据
GET /.git/config

试试

**Comment by lianfeng30** [comment]
生成了
应该是可以 只是提示错误而已吧
