### ISSUE TITLE
小改进

### ISSUE THREAD

**Issue by lupus721** [ysrc/xunfeng#5]
关于 pip那块

pip install -U pip -i https://pypi.douban.com/simple

加上-i参数就可以单次指定源了，还是比较方便的

**Comment by ywolf** [comment]
thanks

**Comment by lupus721** [comment]
wget https://sec.ly.com/mirror/get-pip.py --no-check-certificate
python get-pip.py

这个也可以用
yum install -y python-pip 来完成，你们服务器好慢啊，下载只有一百多k

**Comment by ywolf** [comment]
yum的源都比较老，安装需要最新版本的pip才不会报错

**Comment by lupus721** [comment]
恩，这个倒是，更新那步还是不能省

**Comment by lupus721** [comment]
nohup ./mongod --port 65521 --dbpath DBData &
类似的几个命令都不需要 ./
