### ISSUE TITLE
字典在哪儿？

### ISSUE THREAD

**Issue by 0Mr0** [ysrc/xunfeng#50]
1.19今天下载安装以后界面跟演示视频https://sec-pic-ly.b0.upaiyun.com/xunfeng/xunfeng.mp4
略有不同，测试扫描了一个mysql弱口令，root/root没扫出来，所以想看下字典，但是没有配置字典的地方啊？源码里也没找到。。

**Comment by ihacku** [comment]
配置-扫描引擎-弱口令字典

**Comment by 0Mr0** [comment]
视频里也是这么演示的，但是我装上以后不是这效果，根本就没有扫描引擎。。导航栏都不是横排的，是竖排的。
难道是因为我从中科大pull的镜像？

**Comment by ihacku** [comment]
你可能遇到了假的镜像 哈哈 试试自己搭吧

**Comment by 0Mr0** [comment]
好吧||--||这个镜像可是本项目推荐的安装方式。。rp值真是太低了
谢谢

**Comment by ihacku** [comment]
镜像是第三方提供的呢，是为了方便懒得自己搭的同学试一下用的。

**Comment by 0Mr0** [comment]
哦，明白了

**Comment by 0Mr0** [comment]
我还有个问题，这个创建任务时候貌似不能选取所有脚本啊，只能选一类，比如弱口令

**Comment by 0Mr0** [comment]
最手动搭了一遍，搭完和用docker的镜像一模一样。。。醉了，竟然没有人发现这个问题？？？
