### ISSUE TITLE
最后一步启动不了

### ISSUE THREAD

**Issue by 0Mr0** [ysrc/xunfeng#51]
安装过程没有报任何错，数据能正常导入，但是在最后Run.sh以后浏览器打开127.0.0.1一点反应没有，run.sh里的值也都是根据实际路径做的设置，问题在哪里？
![default](https://cloud.githubusercontent.com/assets/20924821/22097458/287099aa-de5c-11e6-9ee4-650b0428963a.png)

**Comment by ywolf** [comment]
把日志贴出来看一下

**Comment by 0Mr0** [comment]
是我自己的问题，数据库密码没改，现在ok了
