### ISSUE TITLE
没有扫描引擎和爬虫引擎

### ISSUE THREAD

**Issue by 0Mr0** [ysrc/xunfeng#52]
不管是docker镜像安装还是手动配置，“配置”都没有扫描引擎和爬虫引擎，见图
![default](https://cloud.githubusercontent.com/assets/20924821/22141188/c3941e1e-df2b-11e6-9734-4273bb43a8c9.png)

**Comment by ywolf** [comment]
分辨率太低了

**Comment by 0Mr0** [comment]
确实和分别率有关，虽然改了分辨率还是不行，但是最大化就ok了，谢谢~
