### ISSUE TITLE
文档中 mongodb 添加认证不正确

### ISSUE THREAD

**Issue by donghouhe** [ysrc/xunfeng#67]
### 安装文档有出错的地方
- [添加认证](https://github.com/ysrc/xunfeng/blob/master/docs/install/Windows.md#2-mongodb-添加认证) 中

```
$ mongo
> db.createUser({user:'scan',pwd:'your password',roles:[{role:'dbOwner',db:'xunfeng'}]})
> exit
```

mongo 接入该改成

```mongo 127.0.0.1:65521/xunfeng```

即
```
$ mongo 127.0.0.1:65521/xunfeng
> db.createUser({user:'scan',pwd:'your password',roles:[{role:'dbOwner',db:'xunfeng'}]})
```

这样增加的用户才加到了xunfeng这个数据库，原来的那样会加到 test 数据库中
### 测试一下
关闭mongodb后，在参数后加上 --auth 再次启动以启用认证，如
```
mongod --dbpath mongodb --port 65521  --auth
```

终端运行
``` 
mongo 127.0.0.1:65521/xunfeng -u scan -p yourpassword
```

此时能顺利登入即成功了。
### 建议 Run.py 中端口改大
80 端口需 root 权限，建议改大

希望采纳，谢谢！

**Comment by ywolf** [comment]
感谢提醒，已经更正好了。

**Comment by ycjcl868** [comment]
![image](https://cloud.githubusercontent.com/assets/13595509/26274831/c94a4be0-3d85-11e7-82bb-0fdc407de952.png)

**Comment by ywolf** [comment]
连接失败 确定数据库已经启动 并且端口正确

**Comment by ycjcl868** [comment]
数据库已经启动，密码也正确，就是失败
![image](https://cloud.githubusercontent.com/assets/13595509/26283140/89ba9c8a-3e54-11e7-9271-73b0160ff3dd.png)

**Comment by donghouhe** [comment]
端口错误了，你的mongodb在27017端口，你应该改成在65521，或者把连接命令中的 127.0.0.1:65521/xunfeng 改成 127.0.0.1:27017/xunfeng

**Comment by ycjcl868** [comment]
我的锅，解决了。谢谢了
