### ISSUE TITLE
资产扫描ip段每行设置不能大于655360？

### ISSUE THREAD

**Issue by nmweizi** [ysrc/xunfeng#77]
nascan/lib/start.py
if ip_count >= 0 and ip_count <= 655360:
否则会提示IP format error，其实格式没错误，只是有点ip段有点大，建议把提示改下，这个问题困扰了我好久。

看源码，其实是可以用掩码的方式192.0.0.0/8写地址的，建议文档里加上。
if "/" in ip: ip = cidr.CIDR(ip)

**Comment by ywolf** [comment]
建议拆开分，一次性扫描太大的IP段容易出现意外问题，不过提示确实不够清晰。
格式在录入那里的问号有说明的。

**Comment by nmweizi** [comment]
好像只有一种用法的唯有CIDR用法的说明
