### ISSUE TITLE
扫描不知道哪里爆编码错误

### ISSUE THREAD

**Issue by lianfeng30** [ysrc/xunfeng#8]
logerror 'ascii' codec can't encode characters in position 11-14: ordinal not in range(128)
logerror 'ascii' codec can't encode characters in position 11-14: ordinal not in range(128)
logerror 'ascii' codec can't encode characters in position 11-14: ordinal not in range(128)
logerror 'ascii' codec can't encode characters in position 11-14: ordinal not in range(128)
logerror 'ascii' codec can't encode characters in position 11-14: ordinal not in range(128)

**Comment by lianfeng30** [comment]
这个scan.log 日志里面的

**Comment by ywolf** [comment]
nascan/lib/log.py
在
# coding:utf-8 
下面增加

import sys  
reload(sys)  
sys.setdefaultencoding('utf8')

再试试看是否还乱码

**Comment by lianfeng30** [comment]
好的  我试试 谢谢

**Comment by ywolf** [comment]
如果解决了 回复确认一下 我就加上去

**Comment by lupus721** [comment]
确认了，添加以后就不报上面的错了
