### ISSUE TITLE
搜索界面，查询条件仅输入all，查询结果171条，分3页，但点击分页及最后一页无数据

### ISSUE THREAD

**Issue by benny-huang** [ysrc/xunfeng#82]
搜索界面，查询条件仅输入all，查询结果171条，分3页，但点击分页及最后一页无数据。且查询结果中仅包含server:web的部分数据。

**Comment by w298102526** [comment]
我也是这种情况，all后面需要跟内容吧。例如 all:22

**Comment by 404fovnd** [comment]
修改views/static/js/common.js文件，把nextPage和turnTo函数里的if(location.search.length>7)改成if(location.search.length>0)
