### ISSUE TITLE
关于icmp探测bug

### ISSUE THREAD

**Issue by MythHack** [ysrc/xunfeng#86]
如果在配置关闭icmp开启masscan的话，默认还是先icmp探测active 然后在用masscan扫描，而不是扫描全部的ip。
调试了一下发现是在/nascan/lib/start.py:58
```          
            ip_list = self.get_ip_list(ip)
            if self.mode == 1:
                self.masscan_path = self.config_ini['Masscan'].split('|')[2]
                self.masscan_rate = self.config_ini['Masscan'].split('|')[1]
                ip_list = self.get_ac_ip(ip_list)
```
这里并没有判断self.icmp直接去get_ac_ip获取active的ip
加一个判断，就可以修复此问题
```
if self.icmp==1:
    ip_list = self.get_ac_ip(ip_list)
```     
就可以了

**Comment by ywolf** [comment]
title="可启用MASSCAN(自行安装)代替默认的端口扫描方式，路径地址需配置全路径，MASSCAN探测端口范围为1-65535且强制进行ICMP存活检测，请根据网络实际情况设置发包速率。"

masscan是强制ICMP存活检测的，因为全端口扫描比较耗时，如果不开启会浪费非常多的时间和流量，经过权衡还是决定强制ICMP存活检测。

**Comment by MythHack** [comment]
好吧。但是我感觉应该在masscan部分添加开关，实际上也不是很复杂。
因为有一些设备是禁ping的。
