### ISSUE TITLE
如何快速定位到存在漏洞的主机？

### ISSUE THREAD

**Issue by Endt4sk** [ysrc/xunfeng#89]
我在 统计->漏洞分类看到存在漏洞的主机，如何才能快速定位到是哪些主机呢？

在插件里面能看到存在问题的主机，但是点出来查询只是把某个类型的服务全部列出来而已。

**Comment by 0xbug** [comment]
@Endt4sk 任务->点击任务名称

**Comment by ihacku** [comment]
任务哪一页 右上角有个下载 可以导出漏洞数据
