### ISSUE TITLE
error

### ISSUE THREAD

**Issue by MuTouRend** [ysrc/xunfeng#93]
root@MT:/# docker run -d -p 8000:80 -v /opt/data:/data ysrc/xunfeng:latest
7e6537515e91cbf89b507f3591e03404a25de43b91e8d8ef5ea86cfc4733eb0a
FATA[0000] Error response from daemon: Cannot start container 7e6537515e91cbf89b507f3591e03404a25de43b91e8d8ef5ea86cfc4733eb0a: [8] System error: exec format error

**Comment by Medicean** [comment]
@MuTouRend  http://stackoverflow.com/questions/37713604/cannot-start-container-8-system-error-exec-format-error
