### ISSUE TITLE
docker部署怎么修改账号密码

### ISSUE THREAD

**Issue by t4mo** [ysrc/xunfeng#95]
docker部署怎么修改账号密码

**Comment by Medicean** [comment]
> 个人建议体验巡风的时候可以用 Docker，如果体验后觉得很 OK 可以上物理机

关于 Docker 的一些基础操作，建议花 20 分钟时间，边喝咖啡边阅读一下这本书的前 6 章。

[Docker —— 从入门到实践](http://udn.yyuap.com/doc/docker_practice/)

---

然后再来说怎么修改密码吧.

这里我假定你已经把巡风 run 起来了。

1. 查找到 container 的 ID 

```
$ docker ps -a
```

找到巡风对应的 `CONTAINER ID`， 例如 `1f4f1f4f35b2`, 或者用 `NAMES`字段对应的值也成

2. 进入container

```
$ docker exec -i -t 1f4f1f4f35b2 /bin/bash
```
这里的 `1f4f1f4f35b2`就是第一步的那个 ID，用 NAMES 的值也成。

3. 进入巡风目录修改

```
root@1f4f1f4f35b2:/#  cd /opt/xunfeng
```

修改的东西参考物理机上的吧，没`vim`的话就 `apt-get update && apt-get install vim`

4. 退出并重新启动 container

```
root@1f4f1f4f35b2:/#  exit

$ docker restart 1f4f1f4f35b2
```
> 注意上面发的 hostname，`root@1f4f1f4f35b2` 是指在 container 中操作的命令， `$`是在物理机上执行的

最后，Good Luck! @t4mo

**Comment by t4mo** [comment]
Thank

**Comment by 7x4uk4** [comment]
Oh . Good
