### ISSUE TITLE
thread模块没有_count()方法

### ISSUE THREAD

**Issue by cjj0596** [ysrc/xunfeng#96]
我用的是python2.7，上网谷歌过也查过thread模块但是也未能发现thread._count()这个函数，导致扫描引擎线程中止，求解决

**Comment by plane636** [comment]
我在2.6环境下出现同样问题，升级到2.7就没问题了，你可以把2.7升级到最新试一下

**Comment by ihacku** [comment]
安装指南下面有标明需要python 2.7哦
