### ISSUE TITLE
资产探测是否可以根据时间查询

### ISSUE THREAD

**Issue by nmweizi** [ysrc/xunfeng#97]
比如4月10日有次资产扫描，5月20日又有次资产扫描，5月20日的扫描会覆盖资产以前的信息，如何查以前时间的资产扫描结果呢？

**Comment by ywolf** [comment]
在数据库的History表里有保存所有的历史变动信息，只是没有做界面展示。

**Comment by nmweizi** [comment]
ok.如就可以自己查了。
