### ISSUE TITLE
代码有误

### ISSUE THREAD

**Issue by Fankbai** [ysrc/xunfeng#98]
在readme.MD 中Python脚本处,存在一处代码错误. 缺少一个引号

> if user == 'ftp' and pass_ == 'ftp: return u"可匿名登录"'   ####此处位置
>             return u"存在弱口令，账号：%s，密码：%s" % (user, pass_)  # 成功返回结果，内容显示在扫描结果页面。
>

**Comment by ywolf** [comment]
这都被你看出来了
已修改
