### ISSUE TITLE
添加任务时 title空，则后续无法进入该任务

### ISSUE THREAD

**Issue by linger118927** [ysrc/xunfeng#99]
添加任务是如果标题 为空，后续任务结束时 无法进入任务；

可以添加一些空字符的判断，如果title 等一下带超链接的 字符，建议为空时 自己随机几个字符填入
提高可用性

**Comment by ywolf** [comment]
目前是这样 已知问题

**Comment by neargle** [comment]
该问题修复，巡风将会限制空title的任务建立。我们始终觉得一个好的title有助于使用者管理任务，none title 和 random string title 都会对之后的管理产生无法预期的时间支出。感谢提供issue！
